### ISSUE TITLE
What is the purpose of the "use_2dh" option?

### ISSUE THREAD

**Issue by ymjiang** [microsoft/tutel#136]
Hi Tutel authors, thank you for this great framework.

I have a question about commit 901a65cb54c386c8f75bd15e87cf221ff2463d99. What is the purpose of the `use_2dh` option? And what problem does `PrimAllToAll2D` intend to solve? It would be great if you can provide more context. Thanks.

**Comment by ghostplant** [comment]
It is useful in extremely large-scale environments, as it would be be faster than the default one.

**Comment by ymjiang** [comment]
Thank you for the response. Would you please elaborate more about it would be faster? Is it similar to the hierarchical alltoall proposed in DeepSpeed paper?

**Comment by ghostplant** [comment]
PrimAllToAll1D and PrimAllToAll2D don't compute the same output as `torch.distributed.all_to_all_single`, so what do you mean by similar?

**Comment by ghostplant** [comment]
In our paper, PrimAllToAll1D and PrimAllToAll2D are doing a JAX-like dimension swapping based on traditional all to all. You can consult that paper to know more details. I'll close this issue since it is not related to Tutel feature suggestions or bug reports. Thanks!
