### ISSUE TITLE
Implementation of Llama FFN

### ISSUE THREAD

**Issue by pingzhili** [microsoft/tutel#244]
Thanks for the great work!

I don't fully understand the implementation of "llama_ffn" in this repo, specifically, the lines shown below: https://github.com/microsoft/tutel/blob/ac852b3fc9230daf4f765ed929404b7112e83a00/tutel/experts/llama_ffn.py#L38-L41
This is different from the current popular FFN implementation in LLMs (including LLama, https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py), where the activation function works on `y1` and it may look like this:
```
 y = self.activation_fn(y1) * y2
```

I would appreciate any help or guidance on this.

**Comment by ghostplant** [comment]
Hey, thank you! Are you willing to contribute a fix? If no, I'll do an update on this example.

**Comment by pingzhili** [comment]
Sure no problem, I will open a PR here.
